### ISSUE TITLE
when i run "npm start" i get this error...

### ISSUE THREAD

**Issue by OhaaCompany** [Bistard/nota#207]
npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

**Comment by Bistard** [comment]
1. The `README.md` is out-of-date.
2. It should be `npm run script build` and `npm run script run`
3. The project itself is still in progress and nearly functional.
4. We are currently considering a change to close-source.
