### ISSUE TITLE
[UI][NavigationPanel] Sash bar remains interactive after navigation panel collapse

### ISSUE THREAD

**Issue by AAsteria** [Bistard/nota#239]
**Describe the bug**
When the navigation panel is collapsed to the left using the toggle collapse button, the sash bar between the navigation panel and the workspace remains interactive, allowing users to attempt resizing or dragging it. This behavior is unexpected, as collapsing the navigation panel should also disable interactions with the sash bar.

**To Reproduce**

1. Open Nota and navigate to the main view, and remember current position of the sash bar between the navigation panel and workspace.
2. Collapse the navigation panel by clicking the toggle collapse button.
3. Attempt to interact with the transparent sash bar in position in your memory by dragging or clicking on it.
4. Observe that the sash bar still allows user interaction, despite the panel being collapsed.

**Expected behavior**
After collapsing the navigation panel, the sash bar should no longer accept interactions from the user. It should either become inactive or hidden, indicating that no resizing or dragging is possible while the panel is collapsed.

**Screenshots**
Before collapsed:
<img width="1249" alt="Screenshot 2024-11-03 at 20 09 55" src="https://github.com/user-attachments/assets/fd0a6ee6-3ac6-4b5b-8eb1-2b611cf220af">
After collapsed: 
<img width="1249" alt="Screenshot 2024-11-03 at 20 10 01" src="https://github.com/user-attachments/assets/30d5bcc1-a13e-44bd-a461-45f8112ab40f">

**Comment by Bistard** [comment]
哇哦，写的这么详细
