### ISSUE TITLE
[UI][actionBar && tabBar right click will pop up system default context menu]

### ISSUE THREAD

**Issue by Bistard** [Bistard/nota#29]
**Describe the bug**
as the title said.

**Screenshots**
![a6daf700de8db92ba9d17890b0ec005](https://user-images.githubusercontent.com/38385498/130775647-be3fce5c-d8bf-4558-9007-7524e0065172.png)

**Comment by JodyZ0203** [comment]
`40b793b875abf2d4de84bec6f9da81774b5cb056` this commit should fix it.

**Comment by Bistard** [comment]
ancient issue.
